@echo off
echo 🚀 Iniciando servicios de logs...

echo 📦 Instalando dependencias...
pip install -r requirements.txt

echo 🔍 Probando conexiones...
python test_connections.py

echo 🏥 Iniciando API...
python main.py